name: Check Advent-of-Code Solutions

on: [pull_request, workflow_dispatch]

jobs:
  Check-Day:
    runs-on: ubuntu-latest
    container: r-base:latest
    name: ${{ matrix.days.folder }}
    strategy:
      matrix:
        days:
        - {folder: "01", solution_1: 55816, solution_2: 54980}
        - {folder: "02", solution_1: 2913, solution_2: 55593}
        - {folder: "03", solution_1: 531932, solution_2: 73646890}
        - {folder: "04", solution_1: 22674, solution_2: 5747443}
        # - {folder: "05", solution_1: 31599214, solution_2: }
        - {folder: "06", solution_1: 2449062, solution_2: 33149631}
        - {folder: "07", solution_1: 249204891, solution_2: 249666369}
        - {folder: "08", solution_1: 19951, solution_2: 16342438708751}
        - {folder: "09", solution_1: 1731106378, solution_2: 1087}

    steps:
    - uses: actions/checkout@master
    - name: Check Part 1
      run: |
        grep -q "${{ matrix.days.solution_1 }}" <<< "$(Rscript ${{ matrix.days.folder }}/part_1.R)"
      shell: bash {0}
    - name: Check Part 2
      run: |
        grep -q "${{ matrix.days.solution_2 }}" <<< "$(Rscript ${{ matrix.days.folder }}/part_2.R)"
      shell: bash {0}
    
